### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Cheshireknight** [AkramHourani/SEMUS#5]
I tried to use this emulator to create interfered SAR image. But I found the A02_Parameters, FO3_VelocityCheck, NIO1_GenerateA WGN and NIxx_GenerateInterference modules were not uploaded. Or should I create my own noise and interference module?

**Comment by Nermine-Hendy** [comment]
Hi
The simulator has another branch called interference where you will find all the required modules

**Comment by Cheshireknight** [comment]
> Hi The simulator has another branch called interference where you will find all the required modules

Thank you so much for your excellent work.
